### PR TITLE
Create requirements.txt so that dependency can be easily installed

### PR DESCRIPTION
**Pull request by AmgadHasan**
Now we just need to run ```pip install -r requirements.txt```

This will prevent users from installing the wrong libraries.

### CODE REVIEW

**Comment by AmgadHasan** [comment]
@Gldkslfmsd Please check this pr and let me know if changes are needed

**Comment by Gldkslfmsd** [comment]
Thanks! I have following points:

- can you please check if the current versions of these two dependencies limit the current standard Python versions? It means not the very old ones. Is there a serious need to pin specific versions? Look in documentation should be OK.

- `pip install -r requirements.txt` should be mentioned in README.md in Installation section. But the description in this section is already too complicated to add a new alternative way. Can you suggest rewriting of this section?

**Comment by AmgadHasan** [comment]
>     * can you please check if the current versions of these two dependencies limit the current standard Python versions? It means not the very old ones. Is there a serious need to pin specific versions? Look in documentation should be OK.

I took a look at `librosa`'s documentation and they don't mention any specific versions for python so it should be alright.
I'm not sure about `opus-fast-mosestokenizer` though as I am unfamiliar with this package or why it's needed.

>     * `pip install -r requirements.txt` should be mentioned in README.md in Installation section. But the description in this section is already too complicated to add a new alternative way. Can you suggest rewriting of this section?

I updated the readme section, please take a look again.

@Gldkslfmsd

**Comment by Gldkslfmsd** [comment]
Thanks. It needs rewrites, I can do it, but I'm busy now, so I'm leaving it to later.

**Comment by Gldkslfmsd** [comment]
hi,
so, I'm closing this PR, because I integrated and documented the sentence segmenters. Since there are multiple dependency options depending on the languages to be used, I want users to read the documentation and install them manually by themselves, not blindly through requirements.txt.

**Pull request closed without merging**
