### PR TITLE
Warmup file argument

### PR DESCRIPTION
**Pull request by regularfry**
I don't have `cs-maji-2.16k.wav`, and I couldn't immediately see an option for getting it, so I've added a command-line argument for passing in a filename to use for the warmup.

To test, run with `--warmup-file <path to file>`.   I've been using `jfk.wav` from `whisper.cpp` just because I happen to have it handy and it's very short.

### CODE REVIEW

**Comment by Gldkslfmsd** [comment]
hi, thanks.
Can you check whether it has a good impact on the latency? for whisper_timestamped or also for faster-whisper? We shouldn't add features that are not necessary.

**Comment by regularfry** [comment]
Sure, I can give it a look. It seems reasonable that it should to me, but numbers are always better.

**Comment by Gldkslfmsd** [comment]
please, try it without a file: generate audio in the code, like silence or noise, and use it for the warmup. Make sure that it warms up the model, the VAD should not eliminate it.

**Comment by regularfry** [comment]
Ah, ok - if a zeroed out buffer of the right length would do it, that sounds worth trying. Certainly simpler than loading a file.

**Comment by regularfry** [comment]
Interesting results here.  The code I used is [here](https://github.com/regularfry/whisper_streaming/tree/ayo-warmup-benchmark) - that's throwaway code, don't merge it.

I copied `whisper_online_server.py` sideways and made a few minor changes:

- Added a `--whisper-silence` argument to do tell it to do the warmup with a `np.zeros(16000, dtype="float32")` instead of a file
- Added an `--experiment-file` argument to collect results
- Break out of `ServerProcessor#process` as soon as a result comes back from `online.process_iter()` and report how long that took.

Then I ran the server 12 times each for no warmup, warmup with `jfk.wav`, and warmup with silence, each time piping in the audio from another terminal.  The settings that were the same for each run in the first set were:

```
    --model large-v3 \
    --min-chunk-size 1.0 \
    --lan en \
    --task transcribe \
    --buffer_trimming sentence \
    --vad \
    --backend faster-whisper \
    --host 0 \
    --port 2024
```

The results looked like this:

```
No warmup, processing jfk.wav:

887.370915ms
875.938807ms
875.501877ms
845.177832ms
829.329345ms
883.747873ms
882.444844ms
873.820587ms
839.489802ms
877.728412ms
897.142279ms
883.533391ms

Warmup on jfk.wav, processing jfk.wav:

243.015289ms
272.16932ms
263.498096ms
201.77602ms
265.058581ms
275.469426ms
212.245462ms
211.688069ms
209.348139ms
283.600288ms
273.091595ms
190.703303ms

Warmup on silence, processing jfk.wav:

915.181678ms
784.526373ms
873.327527ms
841.010731ms
817.503395ms
847.368157ms
843.501865ms
815.447579ms
798.452904ms
856.67779ms
816.080346ms
792.560641ms
```

Safe to assume all caches were already hot, but we can discard the first two from each run without changing the results.  According to this there's no benefit to warming up on silence, but there *is* a benefit to warming up with actual audio.

I then ran everything again without the `--vad` argument, to see if that was having any effect.  Turns out that it does:

```
No warmup, no VAD, processing jfk.wav:

844.227194ms
833.797763ms
838.973265ms
839.574384ms
850.141796ms
881.373441ms
853.569401ms
862.281172ms
794.07589ms
788.141472ms
848.134715ms

Warmup on jfk.wav, no VAD, processing jfk.wav:

247.576406ms
241.67924ms
205.693126ms
208.547738ms
269.700087ms
194.945033ms
243.253039ms
266.350249ms
221.281746ms
261.34258ms
215.706145ms
262.287681ms

Warmup on silence, no VAD, processing jfk.wav:

622.009106ms
677.61208ms
695.455718ms
670.822408ms
721.766409ms
676.799041ms
663.129363ms
688.335848ms
673.64064ms
624.624806ms
689.414615ms
646.814089ms
```

So warming up on silence has a comparatively small effect on the time-to-first-result, but there's definitely something there.

The system I'm running this on is a core i9-14900K with an RTX4090 and 64GB RAM.

Note that all these numbers are for the first connection to a new server process *only*.  Subsequent connections get the warmed-up latency, but I can think of situations where that might matter.

**Comment by Gldkslfmsd** [comment]
Thanks, this is nice. Let's document it better and merge it.

**Pull request merged**
