### PR TITLE
Create README_CN.md

### PR DESCRIPTION
**Pull request by Gloridust**
I noticed that there are many native Chinese speakers who are interested in this project, but it is still difficult for them to read the English documents. So I wrote a Chinese version of the readme。
Hope u like it.

### CODE REVIEW

**Comment by Gldkslfmsd** [comment]
Hi, thanks. I like your contribution of making easier access to CN speakers, but I can't merge it in this version.
1) I can't take responsibility for correctness, 2) I don't want to annoy the non-CN users with CN version, 3) I can't maintain it, the orig English version can change in future. 

So, I propose you to create a copied repo, named like whisper_streaming_CN. Include an honest and transparent description that it's your amateur translation (or is it machine translation?) of the original English version from [DATE]. 

Then I'll make a new "Useful links" section in my repo README and I'll link your CN repo.

Thanks!

**Review by Gldkslfmsd — CHANGES_REQUESTED** [review]
as commented

**Comment by Gloridust** [comment]
Absolutely! Thank you very much for your reply. I will finalize this in the coming days.

**Comment by Gloridust** [comment]
I have finished most of the work, including the following:

- All translations of "Readme.md"
- Some comments in "whisper_online.py" necessary translations
- The translation of "whisper_online_server.py" is still on the way

You can see my repo here:[Gloridust/whisper_streaming_CN](https://github.com/Gloridust/whisper_streaming_CN)

And add new "Useful link" by [this PR](https://github.com/ufal/whisper_streaming/pull/78) or by your own, both ok.

Love from the other side of the earth.
Hope you like it !

**Pull request closed without merging**
