### PR TITLE
fix: pin silero-vad version to v4

### PR DESCRIPTION
**Pull request by slaesh**
seems there is a new version (v5) which cant handle sample sizes other than 512 for the 16kHz.
let fix it for now to not confuse others who are trying this repo :)

### CODE REVIEW

**Comment by Gldkslfmsd** [comment]
OK, thanks. Citation for your claim needed -- I found the reference here: https://github.com/snakers4/silero-vad/issues/2#issuecomment-2195433115

So this is a hotfix but we should prefer v5 and make it working with the fixed sample window size, right? Do you know how?

**Comment by slaesh** [comment]
`VAD now works with 8 kHz and 16 kHz sample rates, only with fixed 256 and 512 sample windows respectively;`

no unfortunately not, that's why I came up with this first ;)

**Comment by Gldkslfmsd** [comment]
> no unfortunately not, that's why I came up with this first ;)

Then please report it in Siler repo. Thanks!

> but yeah, v5 sounds promising though. might try to chunk the audio and test individual chunks and see if at least one has voice

ok, thanks. Please create an issue or a new PR for that.

**Comment by slaesh** [comment]
> > no unfortunately not, that's why I came up with this first ;)
> 
> Then please report it in Siler repo. Thanks!
> 

what exactly? the issue lies here. the code is working ONLY with v4, but we do not specify the version right now. so we need to do this hotfix until we are ready for v5. :)

**Comment by Gldkslfmsd** [comment]
>> VAD now works with 8 kHz and 16 kHz sample rates, only with fixed 256 and 512 sample windows respectively;

> no unfortunately not, that's why I came up with this first ;)

OK, I thought Siler VAD doesn't work.

**Pull request merged**
